frutas = ["Abacaxi", "Banana", "Caqui"] #Listas
print(frutas)
print(len(frutas), "itens")
frutas.append("Maçã")
print(frutas)
print(len(frutas), "itens")
frutas.insert(1, "Melão")
print(frutas)
print(len(frutas), "itens")
print("_______________________________")
print("O item \"banana\" está na posição:", frutas.index("Banana"))
frutas.remove("Caqui")
print(frutas)
frutas.pop(frutas.index("Banana"))
print(frutas)
frutas.pop()
print(frutas)
frutas.insert(2,"Pera")
frutas.insert(0, "Goiaba")
print(frutas)
frutas.sort()
print(frutas)
frutas.reverse()
print(frutas)